-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.


BEGIN;


DROP TABLE IF EXISTS public.person_skill;
DROP TABLE IF EXISTS public.person;
DROP TABLE IF EXISTS public.skill;


CREATE TABLE IF NOT EXISTS public.person
(
    id serial NOT NULL,
    name character varying(100) NOT NULL,
    age integer NOT NULL,
    avatar_filename character varying(100),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.skill
(
    id serial NOT NULL,
    name character varying(100) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.person_skill
(
    person_id integer NOT NULL,
    skill_id integer NOT NULL,
    PRIMARY KEY (person_id, skill_id)
);

ALTER TABLE IF EXISTS public.person_skill
    ADD CONSTRAINT ps_person_id_fk FOREIGN KEY (person_id)
    REFERENCES public.person (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.person_skill
    ADD CONSTRAINT ps_skill_id_fk FOREIGN KEY (skill_id)
    REFERENCES public.skill (id) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
    NOT VALID;


END;
